### ISSUE TITLE
Remote controller for any android device?

### ISSUE THREAD

**Issue by yunusalih** [rdady/gear-vr-controller-linux#7]
i am not sure if you are still working on this project or not but gearvr controller is really well built and almost absolute now with the dead of gearvr. But it would be great to use this as a slide pointer or as a remote for android tv's or tablets. touc surface as a mouse and trigger as a left click , volume and home buttons etc.

**Comment by rdady** [comment]
Not for for. I worked on a hardware piece based on esp32 but I had no time and I lost interest in it,
Windows port has although landed today.
