### ISSUE TITLE
Porting to Windows

### ISSUE THREAD

**Issue by mikewalshchicago** [rdady/gear-vr-controller-linux#8]
As this is Python, is there any fundamental barriers that prevent this code from working with Windows?  Does windows have a uinput module equivalent that would need to be modified or interfaced with to function?

**Comment by rdady** [comment]
Some python libs I use are not available under Windows, i.e. Bluetooth GATT handling - or maybe I am just not familiar with all of them.
Nevertheless Christmas has come earlier this year: https://github.com/rdady/gear-vr-controller-windows
